---
- name: Install tor browser and required dependencies
  pacman:
    name: '{{ browser_mozilla }}'
    state: present
  become: yes
  tags:
    - browsers
    - tor

- name: Install browsers from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ browser_chrome }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur
    - browsers
