---
- name: Install Utils
  yay:
    name: '{{ utils }}'
    state: present
  become: yes

- include: ntp.yml
- include: pip.yml
- include: zsh.yml
- include: bash.yml
- include: snap.yml
- include: terminator.yml

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/Workspace
    state: directory
  become_user: '{{ user_name }}'
  become: yes
